# Generated by Django 3.1.5 on 2021-03-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=80)),
                ('keterangan', models.CharField(max_length=250)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
